import Link from "next/link";
import { ArrowRight, ArrowUpRight, CalendarDays, Code2, Inbox, Layers3, Users } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";
import { EnquiryDeskPreview } from "@/components/enquiry-desk-preview";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { jsonLd, siteDescription, siteUrl } from "@/lib/site/seo";
import type { Metadata } from "next";

export const metadata: Metadata = { alternates: { canonical: "/" } };

export default function Home() {
  return <div className="product-site"><SiteHeader /><main id="main-content">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd({ "@context": "https://schema.org", "@type": "SoftwareApplication", "@id": `${siteUrl.href}#software`, name: "d3CRM", url: siteUrl.href, description: siteDescription, applicationCategory: "BusinessApplication", operatingSystem: "Web browser", featureList: ["Website contact forms", "Shared enquiry inbox", "Enquiry pipeline", "Follow-up agenda", "Client workspaces", "Campaign reports", "CSV export"], publisher: { "@id": `${siteUrl.href}#organization` } }) }} />
    <section className="product-hero" aria-labelledby="product-title"><div className="hero-copy"><p className="eyebrow"><span className="editorial-mark" aria-hidden>↗</span>THE WEBSITE ENQUIRY WORKSPACE</p><h1 id="product-title">A first <em>hello.</em><br />A clear <span>next step.</span></h1><p className="hero-description">Your website starts the conversation. d3CRM helps your team carry it forward—with one inbox, clear ownership, and follow-ups that stay in view.</p><div className="hero-actions"><Button asChild size="lg"><Link href="/sign-up">Create your workspace <ArrowRight size={16} /></Link></Button><Button asChild variant="outline" size="lg"><Link href="/demo">Try the live demo <ArrowUpRight size={16} /></Link></Button></div><p className="hero-footnote">For small teams, independent studios, and the clients they look after.</p></div><div className="hero-desk"><EnquiryDeskPreview /><p className="preview-caption"><span>01 / THE ENQUIRY DESK</span>Fictional enquiries. Real product flow.</p></div></section>
    <section className="site-workflow" id="product"><div className="site-section-heading"><p className="eyebrow">A LITTLE STRUCTURE. A LOT MORE CLARITY.</p><h2>From “we should reply”<br />to “here’s what’s next.”</h2><p>Three steps that keep good opportunities moving.</p></div><div className="workflow-columns"><article><span className="workflow-number">01 / COLLECT</span><Code2 size={24} /><h3>Give every hello a home.</h3><p>Connect the website you already have. Build a contact form or plug your existing form into d3CRM.</p><Link className="text-link" href="/guides/connect-website-forms">Connect your website <ArrowUpRight size={14} /></Link></article><article><span className="workflow-number">02 / TAKE OWNERSHIP</span><Inbox size={24} /><h3>Know who’s on it.</h3><p>Read the full message, assign a teammate, and move the enquiry from new to contacted to qualified.</p><Link className="text-link" href="/demo">Explore the inbox <ArrowUpRight size={14} /></Link></article><article><span className="workflow-number">03 / FOLLOW THROUGH</span><CalendarDays size={24} /><h3>Make the next step obvious.</h3><p>Keep notes with the conversation and schedule a follow-up. Come back knowing exactly where you left off.</p><Link className="text-link" href="/features">See the workflow <ArrowUpRight size={14} /></Link></article></div></section>
    <section className="site-agencies" id="agencies"><div className="agency-heading"><p className="eyebrow">ONE TEAM. MANY CLIENTS.</p><h2>A dedicated desk<br />for every client.</h2><p>Keep each client’s forms, enquiries, and access in their own workspace. Switch context without losing your rhythm.</p><Button asChild variant="outline"><Link href="/guides/manage-client-enquiries">Explore client workspaces <ArrowUpRight size={16} /></Link></Button></div><div className="client-workspace-preview"><div className="client-preview-label"><Layers3 size={18} /><span>YOUR CLIENT WORKSPACES</span></div>{[{ name: "Fieldwork Studio", type: "Design & development", initial: "F" }, { name: "Northline", type: "Architecture & interiors", initial: "N" }, { name: "Good Company", type: "Independent retail", initial: "G" }].map((client, index) => <div className="client-preview-row" key={client.name}><span className={`client-mark client-mark-${index}`}>{client.initial}</span><span><strong>{client.name}</strong><small>{client.type}</small></span><ArrowUpRight size={17} /></div>)}<p><Users size={16} />Invite the right people. Keep access separate.<span>Illustrative workspaces</span></p></div></section>
    <section className="site-faq"><div className="site-section-heading"><p className="eyebrow">BEFORE YOUR FIRST HELLO</p><h2>A few good questions.</h2><p>Start with a clear picture of how d3CRM fits into your work.</p></div><Accordion type="single" collapsible className="faq-items">{[
      { q: "Does this replace my website?", a: <>Your website stays yours. d3CRM connects to it through an integration snippet or the form submission API.</> },
      { q: "Can I try it without an account?", a: <>Yes. The <Link href="/demo">interactive demo</Link> uses fictional enquiries. Try the inbox, pipeline, assignments, and follow-ups. Changes reset when you reload.</> },
      { q: "Can my clients have their own access?", a: <>Yes. Create a client workspace and invite the people who need it. Each workspace keeps its own forms, enquiries, and permissions.</> },
      { q: "Does d3CRM send replies to my leads?", a: <>The reply composer prepares a personalised draft. Copy it or open it in your email app. You review and send it yourself.</> },
    ].map(({ q, a }, index) => <AccordionItem value={`question-${index}`} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section>
    <div className="site-resource-note"><span>Getting a website ready for launch?</span><Link href="/guides">Read the guides <ArrowUpRight size={14} /></Link><Link href="/tools">Use the free tools <ArrowUpRight size={14} /></Link></div>
    <section className="site-final"><p className="eyebrow">HERE’S TO THE NEXT CONVERSATION.</p><h2>Good enquiries deserve<br />a clear next step.</h2><Button asChild size="lg"><Link href="/sign-up">Make room for yours <ArrowRight size={16} /></Link></Button></section>
  </main><SiteFooter /></div>;
}
