"use client";

import { useRef, useState } from "react";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, CalendarDays, Check, ChevronDown, Columns3, Inbox, LayoutDashboard, List, RotateCcw, Search, X } from "lucide-react";
import { Brand } from "@/components/brand";
import { PageHeader } from "@/components/page-header";
import { WeeklyActivity } from "@/components/weekly-activity";
import { demoLeads, type DemoLead } from "@/lib/demo";

const stages = ["NEW", "CONTACTED", "QUALIFIED", "WON"] as const;
const label = (status: string) => status[0].toUpperCase() + status.slice(1).toLowerCase();

export function ProductDemo() {
  const [leads, setLeads] = useState(demoLeads);
  const [view, setView] = useState("inbox");
  const [layout, setLayout] = useState("list");
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("");
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [menuOpen, setMenuOpen] = useState(false);
  const detail = useRef<HTMLDialogElement>(null);
  const selected = leads.find(lead => lead.id === selectedId);
  const filtered = leads.filter(lead => (!status || lead.status === status) && `${lead.name} ${lead.company} ${lead.message} ${lead.email}`.toLowerCase().includes(query.toLowerCase()));
  const update = (id: number, values: Partial<DemoLead>) => setLeads(current => current.map(lead => lead.id === id ? { ...lead, ...values } : lead));
  const open = (lead: DemoLead) => { setSelectedId(lead.id); update(lead.id, { read: true }); detail.current?.showModal(); };
  const unread = leads.filter(lead => !lead.read).length;
  const followUps = leads.filter(lead => lead.followUp && lead.status !== "WON").sort((a, b) => a.followUp.localeCompare(b.followUp));
  return <div className="app-frame demo-frame"><a className="skip-link" href="#main-content">Skip to content</a>
    <aside className="workspace-sidebar" aria-label="Demo workspace"><div className="sidebar-brand"><Brand href="/" /></div><div className="demo-workspace"><span className="avatar">F</span><span>Fieldwork Studio<small>Sample workspace</small></span></div>
      <div className="mobile-navigation" data-open={menuOpen}><button className="navigation-toggle" aria-expanded={menuOpen} aria-controls="demo-navigation" onClick={() => setMenuOpen(value => !value)}>Workspace menu <ChevronDown size={16} /></button><nav id="demo-navigation" className="app-nav" aria-label="Demo navigation">{[{ id: "overview", title: "Overview", icon: LayoutDashboard }, { id: "inbox", title: "Inbox", icon: Inbox }, { id: "followups", title: "Follow-ups", icon: CalendarDays }].map(({ id, title, icon: Icon }) => <button key={id} className="nav-item" aria-current={view === id ? "page" : undefined} onClick={() => { setView(id); setMenuOpen(false); }}><Icon size={18} /><span>{title}</span>{id === "inbox" && <small>{unread}</small>}</button>)}</nav></div>
      <div className="demo-sidebar-bottom"><Link className="button button-primary button-wide" href="/sign-up">Create workspace <ArrowRight size={16} /></Link><Link className="text-link" href="/">Back to d3CRM <ArrowUpRight size={14} /></Link></div>
    </aside>
    <div className="workspace-body"><header className="workspace-topbar"><span>Workspace <ChevronDown size={14} /><strong>{view === "followups" ? "Follow-ups" : label(view)}</strong></span><span className="demo-topbar-actions"><span className="demo-badge">Demo</span><button className="icon-button" title="Reset demo" aria-label="Reset demo" onClick={() => { setLeads(demoLeads); setQuery(""); setStatus(""); }}><RotateCcw size={16} /></button></span></header>
      <main id="main-content" className="main-content"><div className="page">
        <PageHeader eyebrow="Fieldwork Studio" title={view === "followups" ? "Follow-ups" : label(view)} description={view === "inbox" ? `${filtered.length} ${filtered.length === 1 ? "enquiry" : "enquiries"} · ${unread} unread` : undefined} action={view === "inbox" ? <div className="segmented inbox-layout"><button aria-pressed={layout === "list"} onClick={() => setLayout("list")}><List size={16} />List</button><button aria-pressed={layout === "board"} onClick={() => setLayout("board")}><Columns3 size={16} />Pipeline</button></div> : undefined} />
        {view === "overview" ? <><section className="stats-grid" aria-label="Demo statistics"><button className="stat-card" onClick={() => setView("inbox")}><p>Total enquiries <Inbox size={16} /></p><strong>{leads.length}</strong><small>Across all forms</small></button><button className="stat-card" onClick={() => setView("inbox")}><p>Unread <ArrowUpRight size={16} /></p><strong>{unread}</strong><small>Ready for a first reply</small></button><button className="stat-card" onClick={() => setView("followups")}><p>Scheduled <CalendarDays size={16} /></p><strong>{followUps.length}</strong><small>Upcoming follow-ups</small></button></section><WeeklyActivity demo days={[1, 0, 2, 1, 0, 3, 1].map((total, index) => ({ day: `2026-10-0${index + 1}`, total }))} total={8} won={leads.filter(lead => lead.status === "WON").length} /><div className="overview-grid"><section className="inbox-panel"><div className="panel-header"><h2>Latest enquiries</h2><button className="text-link plain-button" onClick={() => setView("inbox")}>View inbox <ArrowUpRight size={14} /></button></div><div className="list">{leads.slice(0, 5).map(lead => <button className="list-row demo-list-button" key={lead.id} onClick={() => open(lead)}><span className="submission-dot" /><span className="list-main"><strong>{lead.name}</strong><small>{lead.company}</small></span><span className="lead-status" data-status={lead.status}>{label(lead.status)}</span><ArrowRight size={15} /></button>)}</div></section><aside className="overview-followups"><header><h2>Follow-ups</h2></header><ol>{followUps.slice(0, 4).map(lead => <li key={lead.id}><button className="plain-button demo-follow-up" onClick={() => open(lead)}><strong>{lead.name}</strong><span>{lead.company}</span></button><time>{lead.followUp.slice(5)}</time></li>)}</ol></aside></div></> : view === "inbox" ? <>
          <div className="demo-inbox-tools"><label className="demo-search"><Search size={17} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search enquiries…" aria-label="Search demo enquiries" /></label><label className="sr-only" htmlFor="demo-status">Filter by status</label><select id="demo-status" value={status} onChange={event => setStatus(event.target.value)}><option value="">All statuses</option>{stages.map(stage => <option key={stage} value={stage}>{label(stage)}</option>)}</select><span>{filtered.length} {filtered.length === 1 ? "enquiry" : "enquiries"}</span></div>
          {layout === "list" ? <div className="demo-inbox-list"><div className="demo-table-head"><span>Contact</span><span>Form</span><span>Status</span><span>Assigned to</span><span /></div>{filtered.map(lead => <button className="demo-enquiry-row" key={lead.id} onClick={() => open(lead)}><span className="demo-contact"><span className="contact-avatar" data-read={lead.read}>{lead.name.split(" ").map(value => value[0]).join("")}</span><span><strong>{lead.name}{!lead.read && <i className="unread-dot" />}</strong><small>{lead.company}</small></span></span><span>{lead.form}</span><span className="lead-status" data-status={lead.status}>{label(lead.status)}</span><span>{lead.assignee}</span><ArrowUpRight size={15} /></button>)}{!filtered.length && <p className="demo-empty">No matching enquiries</p>}</div> : <div className="pipeline-board">{stages.filter(stage => !status || stage === status).map(stage => <section className="pipeline-stage" key={stage}><header><h2 className="lead-status" data-status={stage}>{label(stage)}</h2><span>{filtered.filter(lead => lead.status === stage).length}</span></header><div className="pipeline-leads">{filtered.filter(lead => lead.status === stage).map(lead => <article className="pipeline-lead" key={lead.id}><button className="plain-button demo-pipeline-contact" onClick={() => open(lead)}><strong>{lead.name}</strong><span>{lead.company}</span></button><p>{lead.message}</p><small>{lead.assignee}</small><select aria-label={`Status for ${lead.name}`} value={lead.status} onChange={event => update(lead.id, { status: event.target.value as DemoLead["status"] })}>{stages.map(value => <option key={value} value={value}>{label(value)}</option>)}</select></article>)}</div></section>)}</div>}
        </> : <div className="demo-followups-list">{followUps.map(lead => <div className="follow-up-row" key={lead.id}><div className="follow-up-contact"><button className="plain-button" onClick={() => open(lead)}><strong>{lead.name}</strong></button><span>{lead.company}</span></div><time>{lead.followUp}</time><label className="field"><span className="sr-only">Follow-up for {lead.name}</span><input type="date" aria-label={`Follow-up for ${lead.name}`} value={lead.followUp} onChange={event => update(lead.id, { followUp: event.target.value })} /></label></div>)}{!followUps.length && <p>No scheduled follow-ups</p>}</div>}
      </div></main>
    </div>
    <dialog ref={detail} className="demo-detail-dialog" aria-labelledby="demo-detail-title" onClick={event => { if (event.target === detail.current) detail.current.close(); }}>
      {selected && <div className="demo-detail-surface"><header><span className="eyebrow">{selected.form}</span><button className="icon-button" title="Close enquiry" aria-label="Close enquiry" onClick={() => detail.current?.close()}><X size={18} /></button></header><h2 id="demo-detail-title">{selected.name}</h2><p>{selected.company} · {selected.email}</p><blockquote>{selected.message}</blockquote><div className="two-fields"><label className="field"><span>Status</span><select value={selected.status} onChange={event => update(selected.id, { status: event.target.value as DemoLead["status"] })}>{stages.map(stage => <option key={stage} value={stage}>{label(stage)}</option>)}</select></label><label className="field"><span>Assigned to</span><select value={selected.assignee} onChange={event => update(selected.id, { assignee: event.target.value })}>{["Unassigned", "Alex", "Jamie"].map(name => <option key={name}>{name}</option>)}</select></label></div><label className="field"><span>Follow-up date</span><input type="date" value={selected.followUp} onChange={event => update(selected.id, { followUp: event.target.value })} /></label><button className="button button-primary" onClick={() => detail.current?.close()}><Check size={16} />Done</button></div>}
    </dialog>
  </div>;
}
