"use client";
import { Tooltip, TooltipTrigger, TooltipContent } from "@/components/ui/tooltip";

import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription, SheetTrigger } from "@/components/ui/sheet";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";

import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, CalendarDays, Check, ChevronDown, Columns3, Inbox, LayoutDashboard, List, RotateCcw, Search, X } from "lucide-react";
import { Brand } from "@/components/brand";
import { PageHeader } from "@/components/page-header";
import { WeeklyActivity } from "@/components/weekly-activity";
import { demoLeads, type DemoLead } from "@/lib/demo";

const stages = ["NEW", "CONTACTED", "QUALIFIED", "WON"] as const;
const label = (status: string) => status[0].toUpperCase() + status.slice(1).toLowerCase();

export function ProductDemo() {
  const [leads, setLeads] = useState(demoLeads);
  const [view, setView] = useState("inbox");
  const [layout, setLayout] = useState("list");
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("");
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [menuOpen, setMenuOpen] = useState(false);

  const selected = leads.find(lead => lead.id === selectedId);
  const filtered = leads.filter(lead => (!status || lead.status === status) && `${lead.name} ${lead.company} ${lead.message} ${lead.email}`.toLowerCase().includes(query.toLowerCase()));
  const update = (id: number, values: Partial<DemoLead>) => setLeads(current => current.map(lead => lead.id === id ? { ...lead, ...values } : lead));
  const open = (lead: DemoLead) => { setSelectedId(lead.id); update(lead.id, { read: true });  };
  const unread = leads.filter(lead => !lead.read).length;
  const followUps = leads.filter(lead => lead.followUp && lead.status !== "WON").sort((a, b) => a.followUp.localeCompare(b.followUp));
  const navigation = <nav className="app-nav" aria-label="Demo navigation">{[{ id: "overview", title: "Overview", icon: LayoutDashboard }, { id: "inbox", title: "Inbox", icon: Inbox }, { id: "followups", title: "Follow-ups", icon: CalendarDays }].map(({ id, title, icon: Icon }) => <Button variant="ghost" key={id} className="nav-item" aria-current={view === id ? "page" : undefined} onClick={() => { setView(id); setMenuOpen(false); }}><Icon size={18} /><span>{title}</span>{id === "inbox" && <small>{unread}</small>}</Button>)}</nav>;
  return <div className="app-frame demo-frame"><a className="skip-link" href="#main-content">Skip to content</a>
    <aside className="workspace-sidebar" aria-label="Demo workspace"><div className="sidebar-brand"><Brand href="/" /></div><div className="demo-workspace"><span className="avatar">F</span><span>Fieldwork Studio<small>Sample workspace</small></span></div>
      <div className="demo-desktop-navigation">{navigation}</div><div className="mobile-navigation"><Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetTrigger asChild><Button variant="outline" className="navigation-toggle">Workspace menu <ChevronDown size={16} /></Button></SheetTrigger><SheetContent side="left" className="mobile-workspace-menu"><SheetHeader><SheetTitle>Fieldwork Studio</SheetTitle><SheetDescription>Explore the sample workspace.</SheetDescription></SheetHeader>{navigation}</SheetContent></Sheet></div>
      <div className="demo-sidebar-bottom"><Button asChild variant="default"><Link className="button button-primary button-wide" href="/sign-up">Create workspace <ArrowRight size={16} /></Link></Button><Link className="text-link" href="/">Back to d3CRM <ArrowUpRight size={14} /></Link></div>
    </aside>
    <div className="workspace-body"><header className="workspace-topbar"><span>Workspace <ChevronDown size={14} /><strong>{view === "followups" ? "Follow-ups" : label(view)}</strong></span><span className="demo-topbar-actions"><Badge variant="secondary" className="demo-badge">Demo</Badge><Tooltip><TooltipTrigger asChild><Button variant="ghost" size="icon" className="icon-button" aria-label="Reset demo" onClick={() => { setLeads(demoLeads); setQuery(""); setStatus(""); }}><RotateCcw size={16} /></Button></TooltipTrigger><TooltipContent>{"Reset demo"}</TooltipContent></Tooltip></span></header>
      <main id="main-content" className="main-content"><div className="page">
        <PageHeader eyebrow="Fieldwork Studio" title={view === "followups" ? "Follow-ups" : label(view)} description={view === "inbox" ? `${filtered.length} ${filtered.length === 1 ? "enquiry" : "enquiries"} · ${unread} unread` : undefined} action={view === "inbox" ? <ToggleGroup type="single" value={layout} onValueChange={value => { if (value) setLayout(value); }} aria-label="Inbox layout"><ToggleGroupItem value="list"><List size={16} />List</ToggleGroupItem><ToggleGroupItem value="board"><Columns3 size={16} />Pipeline</ToggleGroupItem></ToggleGroup> : undefined} />
        {view === "overview" ? <><section className="stats-grid" aria-label="Demo statistics"><Button variant="ghost" className="stat-card" onClick={() => setView("inbox")}><p>Total enquiries <Inbox size={16} /></p><strong>{leads.length}</strong><small>Across all forms</small></Button><Button variant="ghost" className="stat-card" onClick={() => setView("inbox")}><p>Unread <ArrowUpRight size={16} /></p><strong>{unread}</strong><small>Ready for a first reply</small></Button><Button variant="ghost" className="stat-card" onClick={() => setView("followups")}><p>Scheduled <CalendarDays size={16} /></p><strong>{followUps.length}</strong><small>Upcoming follow-ups</small></Button></section><WeeklyActivity demo days={[1, 0, 2, 1, 0, 3, 1].map((total, index) => ({ day: `2026-10-0${index + 1}`, total }))} total={8} won={leads.filter(lead => lead.status === "WON").length} /><div className="overview-grid"><Card className="inbox-panel"><div className="panel-header"><h2>Latest enquiries</h2><Button variant="ghost" className="text-link plain-button" onClick={() => setView("inbox")}>View inbox <ArrowUpRight size={14} /></Button></div><div className="list">{leads.slice(0, 5).map(lead => <Button variant="ghost" className="list-row demo-list-button" key={lead.id} onClick={() => open(lead)}><span className="submission-dot" /><span className="list-main"><strong>{lead.name}</strong><small>{lead.company}</small></span><Badge variant="secondary" className="lead-status" data-status={lead.status}>{label(lead.status)}</Badge><ArrowRight size={15} /></Button>)}</div></Card><aside className="overview-followups"><header><h2>Follow-ups</h2></header><ol>{followUps.slice(0, 4).map(lead => <li key={lead.id}><Button variant="ghost" className="plain-button demo-follow-up" onClick={() => open(lead)}><strong>{lead.name}</strong><span>{lead.company}</span></Button><time>{lead.followUp.slice(5)}</time></li>)}</ol></aside></div></> : view === "inbox" ? <>
          <div className="demo-inbox-tools"><Label className="demo-search"><Search size={17} /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search enquiries…" aria-label="Search demo enquiries" /></Label><Label className="sr-only" htmlFor="demo-status">Filter by status</Label><NativeSelect id="demo-status" value={status} onChange={event => setStatus(event.target.value)}><NativeSelectOption value="">All statuses</NativeSelectOption>{stages.map(stage => <NativeSelectOption key={stage} value={stage}>{label(stage)}</NativeSelectOption>)}</NativeSelect><span>{filtered.length} {filtered.length === 1 ? "enquiry" : "enquiries"}</span></div>
          {layout === "list" ? <div className="demo-inbox-list"><div className="demo-table-head"><span>Contact</span><span>Form</span><span>Status</span><span>Assigned to</span><span /></div>{filtered.map(lead => <Button variant="ghost" className="demo-enquiry-row" key={lead.id} onClick={() => open(lead)}><span className="demo-contact"><span className="contact-avatar" data-read={lead.read}>{lead.name.split(" ").map(value => value[0]).join("")}</span><span><strong>{lead.name}{!lead.read && <i className="unread-dot" />}</strong><small>{lead.company}</small></span></span><span>{lead.form}</span><Badge variant="secondary" className="lead-status" data-status={lead.status}>{label(lead.status)}</Badge><span>{lead.assignee}</span><ArrowUpRight size={15} /></Button>)}{!filtered.length && <p className="demo-empty">No matching enquiries</p>}</div> : <div className="pipeline-board">{stages.filter(stage => !status || stage === status).map(stage => <section className="pipeline-stage" key={stage}><header><Badge variant="secondary" className="lead-status" data-status={stage}>{label(stage)}</Badge><span>{filtered.filter(lead => lead.status === stage).length}</span></header><div className="pipeline-leads">{filtered.filter(lead => lead.status === stage).map(lead => <article className="pipeline-lead" key={lead.id}><Button variant="ghost" className="plain-button demo-pipeline-contact" onClick={() => open(lead)}><strong>{lead.name}</strong><span>{lead.company}</span></Button><p>{lead.message}</p><small>{lead.assignee}</small><NativeSelect aria-label={`Status for ${lead.name}`} value={lead.status} onChange={event => update(lead.id, { status: event.target.value as DemoLead["status"] })}>{stages.map(value => <NativeSelectOption key={value} value={value}>{label(value)}</NativeSelectOption>)}</NativeSelect></article>)}</div></section>)}</div>}
        </> : <div className="demo-followups-list">{followUps.map(lead => <div className="follow-up-row" key={lead.id}><div className="follow-up-contact"><Button variant="ghost" className="plain-button" onClick={() => open(lead)}><strong>{lead.name}</strong></Button><span>{lead.company}</span></div><time>{lead.followUp}</time><Label className="field"><span className="sr-only">Follow-up for {lead.name}</span><Input type="date" aria-label={`Follow-up for ${lead.name}`} value={lead.followUp} onChange={event => update(lead.id, { followUp: event.target.value })} /></Label></div>)}{!followUps.length && <p>No scheduled follow-ups</p>}</div>}
      </div></main>
    </div>
    <Dialog open={selectedId !== null} onOpenChange={next => { if (!next) setSelectedId(null); }}><DialogContent className="demo-detail-content" showCloseButton={false}><DialogHeader className="sr-only"><DialogTitle>Enquiry details</DialogTitle><DialogDescription>Review the message, update its status, and plan a follow-up.</DialogDescription></DialogHeader>
      {selected && <div className="demo-detail-surface"><header><span className="eyebrow">{selected.form}</span><Tooltip><TooltipTrigger asChild><Button variant="ghost" size="icon" className="icon-button" aria-label="Close enquiry" onClick={() => setSelectedId(null)}><X size={18} /></Button></TooltipTrigger><TooltipContent>{"Close enquiry"}</TooltipContent></Tooltip></header><h2 id="demo-detail-title">{selected.name}</h2><p>{selected.company} · {selected.email}</p><blockquote>{selected.message}</blockquote><div className="two-fields"><Label className="field"><span>Status</span><NativeSelect aria-label="Status" value={selected.status} onChange={event => update(selected.id, { status: event.target.value as DemoLead["status"] })}>{stages.map(stage => <NativeSelectOption key={stage} value={stage}>{label(stage)}</NativeSelectOption>)}</NativeSelect></Label><Label className="field"><span>Assigned to</span><NativeSelect aria-label="Assigned to" value={selected.assignee} onChange={event => update(selected.id, { assignee: event.target.value })}>{["Unassigned", "Alex", "Jamie"].map(name => <NativeSelectOption key={name}>{name}</NativeSelectOption>)}</NativeSelect></Label></div><Label className="field"><span>Follow-up date</span><Input type="date" value={selected.followUp} onChange={event => update(selected.id, { followUp: event.target.value })} /></Label><Button variant="default" className="button button-primary" onClick={() => setSelectedId(null)}><Check size={16} />Done</Button></div>}
    </DialogContent></Dialog>
  </div>;
}
