export type DemoLead = { id: number; name: string; company: string; email: string; message: string; form: string; status: "NEW" | "CONTACTED" | "QUALIFIED" | "WON"; assignee: string; followUp: string; read: boolean };

// Fictional examples only. The public demo never connects to a workspace database.
export const demoLeads: DemoLead[] = [
  { id: 1, name: "Olivia Chen", company: "Fieldwork Studio", email: "olivia@example.test", message: "We're launching a new collection in November and need a website that brings it to life. Are you available for a quick call this week?", form: "Project enquiries", status: "NEW", assignee: "Unassigned", followUp: "2026-10-05", read: false },
  { id: 2, name: "James Wilson", company: "Northline", email: "james@example.test", message: "Our team is looking for a design partner for our new site. We'd love to see your availability and a rough proposal.", form: "Project enquiries", status: "QUALIFIED", assignee: "Alex", followUp: "2026-10-06", read: true },
  { id: 3, name: "Priya Shah", company: "Common Ground", email: "priya@example.test", message: "We need a better booking experience for our community workshops. Could we talk through the options?", form: "Book a consultation", status: "NEW", assignee: "Alex", followUp: "2026-10-07", read: false },
  { id: 4, name: "Noah Williams", company: "Forma Architects", email: "noah@example.test", message: "We'd like to refresh our portfolio before the end of the year. We have photography ready and a clear brief.", form: "Project enquiries", status: "CONTACTED", assignee: "Jamie", followUp: "2026-10-08", read: true },
  { id: 5, name: "Amelia Reed", company: "Goodside", email: "amelia@example.test", message: "Thanks for the proposal. We're happy to move forward with the brand and website project.", form: "Project enquiries", status: "WON", assignee: "Alex", followUp: "", read: true },
  { id: 6, name: "Leo Martin", company: "Morrow Coffee", email: "leo@example.test", message: "We're opening a second location and want a simple, well-designed site. What's your usual process?", form: "Book a consultation", status: "NEW", assignee: "Unassigned", followUp: "", read: false },
  { id: 7, name: "Sofia Garcia", company: "Gather", email: "sofia@example.test", message: "Could you help us bring our events programme online? We'd like to make enquiries easier for organisers.", form: "Project enquiries", status: "CONTACTED", assignee: "Jamie", followUp: "2026-10-09", read: true },
  { id: 8, name: "Oliver Park", company: "Tandem", email: "oliver@example.test", message: "We have a product launch coming up and need a focused landing page. Our target date is next month.", form: "Project enquiries", status: "QUALIFIED", assignee: "Alex", followUp: "2026-10-10", read: true },
];
