import Link from "next/link";
import { LegalContact, LegalDocument } from "@/components/legal-document";
import { publicMetadata } from "@/lib/site/seo";

export const dynamic = "force-dynamic";
export const metadata = publicMetadata("Account Data Notice", "The information d3CRM needs to create and operate your account, and how to withdraw account consent.", "/account-data-notice");

export default function AccountDataNotice() {
  return <LegalDocument title="Account Data Notice" intro="Before you create an account, please read how we use the information you provide. This notice describes the account processing covered by the separate signup consent.">
    <section className="resource-section"><h2>Information and purposes</h2><ul><li><strong>Your name:</strong> identify you to workspace teammates and attribute your actions.</li><li><strong>Email address:</strong> sign in, verify your address, recover your password, receive invitations, and send essential account messages.</li><li><strong>Password:</strong> authenticate you. We store a password hash rather than your readable password.</li><li><strong>Organization name and workspace membership:</strong> create your workspace and control which records you can access.</li><li><strong>Acceptance and consent records:</strong> record the notice and terms version and the time of your choices.</li></ul><p>We use these details to provide your account and shared enquiry workspace. Authorized teammates can see your name, email, role, and relevant activity. Hosting/database providers process the stored details; our configured email provider, Resend, receives addresses and essential email messages. See the <Link href="/privacy#providers">provider and location disclosure</Link>.</p></section>
    <section className="resource-section"><h2>Your choice</h2><p>The account fields are required to provide this service. You may decline and use public resources without an account. Account consent is separate from accepting the terms and does not permit advertising, marketing messages, AI training, or collecting information from your website visitors.</p><p>To withdraw, send a request to the privacy email below from your account email with the subject “Withdraw account consent”. You do not need to give a reason or contact a workspace owner for permission. We will stop processing that depends on consent and arrange account closure; you will lose account access. We explain any narrow legal retention requirement. Withdrawal does not undo processing already carried out lawfully.</p></section>
    <section className="resource-section"><h2>Rights and complaints</h2><p>Use the same contact to request access, correction, erasure, or help with a complaint. We handle requests within applicable legal deadlines. In India, DPDP rights, nomination, and escalation to the Data Protection Board apply as the relevant provisions commence. You may use other competent regulators where applicable; see <Link href="/privacy#rights">regional rights and complaint routes</Link>. Ask for this notice in Hindi or another language in the Constitution’s Eighth Schedule if needed; we will arrange the version required by applicable law.</p></section>
    <LegalContact />
  </LegalDocument>;
}
