import assert from "node:assert/strict";
import { hash, compare } from "bcryptjs";
import { db } from "../lib/db.ts";
import { createFormKey } from "../lib/keys.ts";
import { rateLimit } from "../lib/rate-limit.ts";
import { decrypt, encrypt, randomToken, tokenHash } from "../lib/security.ts";
import { mailJob, processDeliveries } from "../lib/deliveries.ts";
import { checkQuota, verifyStripeSignature } from "../lib/billing.ts";
import { webhookSignature } from "../lib/security.ts";
import { addLeadNote, bulkSaveLeads, removeLead, saveLead } from "../lib/lead-workflow.ts";
import { removeInboxView, saveInboxView } from "../lib/inbox.ts";
import { leadReport, reportRange } from "../lib/reports.ts";
import { clientInput, clientWorkspaces, createClientWorkspace } from "../lib/workspaces.ts";
import { queueUnassignedAlerts, saveRouting } from "../lib/assignment.ts";
import { removeReplyTemplate, saveReplyTemplate } from "../lib/reply-templates.ts";
import { primaryContactEmail } from "../lib/forms/contact.ts";
import { relatedEnquiries } from "../lib/duplicate-leads.ts";
import { duplicateFormInWorkspace } from "../lib/forms/duplicate.ts";
import { followUpAgenda } from "../lib/follow-ups.ts";
import { followUpFilters } from "../lib/follow-up-filters.ts";

const base = process.env.NEXTAUTH_URL!;
const url = new URL(process.env.DATABASE_URL!);
if (!["localhost", "127.0.0.1"].includes(url.hostname) || !url.pathname.endsWith("_test") || !["localhost", "127.0.0.1"].includes(new URL(base).hostname)) throw new Error("Integration checks require a local test database and server.");
const suffix = randomToken().slice(0, 10).toLowerCase();
const userIds: string[] = []; const orgIds: string[] = []; const jobIds: string[] = [];

class Client {
  cookies = new Map<string, string>();
  async fetch(path: string, init: RequestInit = {}) {
    const headers = new Headers(init.headers);
    headers.set("Cookie", [...this.cookies].map(([key, value]) => `${key}=${value}`).join("; "));
    const response = await fetch(`${base}${path}`, { ...init, headers, redirect: "manual" });
    for (const cookie of response.headers.getSetCookie()) {
      const [pair] = cookie.split(";"); const index = pair.indexOf("="); this.cookies.set(pair.slice(0, index), pair.slice(index + 1));
    }
    return response;
  }
  async login(email: string, password: string) {
    const csrf = await (await this.fetch("/api/auth/csrf")).json();
    const response = await this.fetch("/api/auth/callback/credentials", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded", Origin: base }, body: new URLSearchParams({ csrfToken: csrf.csrfToken, email, password, callbackUrl: `${base}/dashboard`, json: "true" }) });
    assert.equal(response.status, 200);
    assert.ok(this.cookies.has("next-auth.session-token"), "Login must issue a session");
  }
  async post(path: string, body: unknown) {
    return this.fetch(path, { method: "POST", headers: { Origin: base, "Content-Type": "application/json" }, body: JSON.stringify(body) });
  }
}

async function fixture(name: string, role: "OWNER" | "ADMIN" | "VIEWER" | "MEMBER" = "OWNER", organizationId?: string) {
  const user = await db.user.create({ data: { name, email: `${name.toLowerCase()}-${suffix}@example.test`, passwordHash: await hash("IntegrationPassword2026!", 12), emailVerifiedAt: new Date() } }); userIds.push(user.id);
  const org = organizationId ? null : await db.organization.create({ data: { name: `${name} ${suffix}`, slug: `${name.toLowerCase()}-${suffix}` } });
  if (org) orgIds.push(org.id);
  await db.organizationMember.create({ data: { userId: user.id, organizationId: organizationId ?? org!.id, role } });
  return { user, organizationId: organizationId ?? org!.id };
}

try {
  const owner = await fixture("Owner"); const outsider = await fixture("Outsider");
  const ownerClient = new Client(); const outsiderClient = new Client(); const anonymous = new Client();
  await ownerClient.login(owner.user.email, "IntegrationPassword2026!");
  await outsiderClient.login(outsider.user.email, "IntegrationPassword2026!");
  const key = createFormKey();
  const schema = { version: 1, fields: [{ id: "name", label: "Original name", type: "text", required: true }, { id: "email", label: "Email", type: "email", required: true }, { id: "message", label: "Message", type: "textarea", required: true, maxLength: 1000 }] };
  const form = await db.form.create({ data: { name: "Integration enquiries", slug: `integration-${suffix}`, organizationId: owner.organizationId, schema, keyHash: key.hash, keyPrefix: key.prefix, notificationEmails: [owner.user.email], allowedOrigins: ["https://allowed.example"] } });
  const submit = (data: unknown, origin = "https://allowed.example", formKey = key.key) => fetch(`${base}/api/v1/forms/${form.slug}/submissions`, { method: "POST", headers: { Origin: origin, "X-Form-Key": formKey, "Content-Type": "application/json" }, body: JSON.stringify(data) });
  const payload = { name: "Test enquiry", email: "lead@example.test", message: " =HYPERLINK(\"example\")" };
  assert.equal((await submit(payload, "https://evil.example")).status, 403);
  assert.equal((await submit(payload, undefined, "invalid")).status, 404);
  assert.equal((await submit({ ...payload, email: "bad" })).status, 422);
  assert.equal((await submit({ ...payload, message: "   " })).status, 422);
  assert.equal((await submit({ ...payload, _gotcha: "bot" })).status, 202);
  assert.equal(await db.submission.count({ where: { formId: form.id } }), 0);
  assert.equal((await submit({ ...payload, message: "x".repeat(70_000) })).status, 413);
  assert.equal((await submit({ ...payload, _context: { landing_page: "javascript:alert(1)" } })).status, 422);
  const accepted = await submit({ ...payload, email: "LEAD@Example.Test", _context: { landing_page: "https://allowed.example/contact?token=private&utm_source=Google", utm_source: "Google", utm_medium: "CPC", utm_campaign: "Studio launch" } }); assert.equal(accepted.status, 201);
  const lead = (await accepted.json()).submission;
  const saved = await db.submission.findUniqueOrThrow({ where: { id: lead.id } });
  assert.deepEqual(saved.schemaSnapshot, schema);
  assert.equal(saved.contactEmail, "lead@example.test");
  assert.equal((saved.data as Record<string, unknown>).email, "LEAD@Example.Test", "Contact normalization must not alter stored answers");
  assert.deepEqual(saved.attribution, { landing_page: "https://allowed.example/contact", utm_source: "google", utm_medium: "cpc", utm_campaign: "Studio launch" });
  assert.equal(await db.activity.count({ where: { submissionId: lead.id, action: "lead.created" } }), 1);
  assert.ok(!Object.keys(saved.data as object).includes("_context"));
  assert.equal(await db.outboundDelivery.count({ where: { submissionId: lead.id } }), 1);
  console.log("PASS submission validation, origins, honeypot, payload limits, durable alerts");

  const state = { status: "CONTACTED" as const, assigneeId: owner.user.id, followUpAt: new Date(Date.now() - 86400_000), updatedAt: saved.updatedAt, unread: false };
  await assert.rejects(() => db.$transaction(tx => saveLead(tx, outsider.organizationId, outsider.user.id, lead.id, state)), { status: 404 });
  const changes = await Promise.allSettled([db.$transaction(tx => saveLead(tx, owner.organizationId, owner.user.id, lead.id, state)), db.$transaction(tx => saveLead(tx, owner.organizationId, owner.user.id, lead.id, state))]);
  assert.equal(changes.filter(change => change.status === "fulfilled").length, 1);
  const contacted = await db.submission.findUniqueOrThrow({ where: { id: lead.id } });
  assert.ok(contacted.firstContactedAt);
  assert.equal(await db.activity.count({ where: { submissionId: lead.id, action: "lead.updated" } }), 1);
  await db.$transaction(tx => saveLead(tx, owner.organizationId, owner.user.id, lead.id, { ...state, status: "WON", updatedAt: contacted.updatedAt }));
  assert.equal((await db.submission.findUniqueOrThrow({ where: { id: lead.id } })).firstContactedAt!.getTime(), contacted.firstContactedAt.getTime());
  await db.$transaction(tx => addLeadNote(tx, owner.organizationId, owner.user.id, lead.id, "Private note must stay out of audit metadata."));
  const activity = await db.activity.findMany({ where: { submissionId: lead.id } });
  assert.ok(!JSON.stringify(activity).includes("Private note") && !JSON.stringify(activity).includes("lead@example.test"));
  const range = reportRange();
  const report = await leadReport(owner.organizationId, range);
  assert.equal(report.totals.total, 1); assert.equal(report.totals.won, 1); assert.equal(report.totals.contacted, 1);
  assert.equal(report.sources[0].source, "google"); assert.equal(report.forms[0].id, form.id);
  assert.equal((await leadReport(outsider.organizationId, range, form.id)).totals.total, 0);
  const viewer = await fixture("Viewer", "VIEWER", owner.organizationId); const viewerClient = new Client();
  await viewerClient.login(viewer.user.email, "IntegrationPassword2026!");
  const viewerActivity = await viewerClient.fetch("/activity"); const viewerActivityBody = await viewerActivity.text();
  assert.ok(viewerActivity.status === 307 || viewerActivityBody.includes("NEXT_REDIRECT;replace;/dashboard;307;"));
  assert.ok(!viewerActivityBody.includes("Enquiry received"));
  assert.equal((await viewerClient.fetch("/reports")).status, 200);
  assert.equal((await outsiderClient.fetch(`/reports?form=${form.id}`)).status, 200);
  const outsideActivity = await outsiderClient.fetch("/activity");
  assert.ok(!(await outsideActivity.text()).includes("Enquiry received"));
  const reportPage = await ownerClient.fetch("/reports"); assert.equal(reportPage.status, 200); assert.ok((await reportPage.text()).includes("google"));
  console.log("PASS atomic activity history, contact timestamps, tenant-scoped reports and audit permissions");

  await db.form.update({ where: { id: form.id }, data: { schema: { version: 1, fields: [{ id: "company", label: "Company", type: "text", required: true }] }, schemaVersion: { increment: 1 } } });
  const oldDetail = await ownerClient.fetch(`/submissions/${lead.id}`); assert.equal(oldDetail.status, 200); assert.ok((await oldDetail.text()).includes("Original name"));
  const formPage = await ownerClient.fetch(`/forms/${form.id}`); const formBody = await formPage.text(); assert.ok(formBody.includes("Original name") && formBody.includes("Test enquiry"));
  const dashboard = await ownerClient.fetch("/dashboard"); assert.ok((await dashboard.text()).includes(`/submissions/${lead.id}`));
  const deniedDetail = await outsiderClient.fetch(`/submissions/${lead.id}`);
  const deniedBody = await deniedDetail.text();
  assert.ok(deniedBody.includes("This page could not be found."));
  assert.ok(!deniedBody.includes("Original name") && !deniedBody.includes("Test enquiry"));
  assert.equal((await outsiderClient.fetch(`/api/forms/${form.id}/export`)).status, 404);
  const exported = await ownerClient.fetch(`/api/forms/${form.id}/export`); assert.equal(exported.status, 200); const csv = await exported.text(); assert.ok(csv.includes('"name"')); assert.ok(csv.includes('"company"')); assert.ok(csv.includes("'=HYPERLINK"));
  assert.ok(csv.includes('"_context.utm_source"') && csv.includes('"google"'));
  assert.equal(await db.activity.count({ where: { organizationId: owner.organizationId, action: "form.exported" } }), 1);
  assert.equal((await anonymous.fetch("/submissions")).status, 307);
  console.log("PASS workspace isolation, historical schemas, safe CSV exports");

  const attempts = await Promise.allSettled(Array.from({ length: 30 }, () => rateLimit(`concurrent-${suffix}`, "same-client", 10, 60)));
  assert.equal(attempts.filter(result => result.status === "fulfilled").length, 10);
  console.log("PASS concurrent rate limits allow exactly the configured number");

  const invalidOrigin = await fetch(`${base}/api/auth/register`, { method: "POST", headers: { Origin: "https://evil.example", "Content-Type": "application/json" }, body: "{}" }); assert.equal(invalidOrigin.status, 403);
  const oversizedAuth = await fetch(`${base}/api/auth/callback/credentials`, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: "x".repeat(9000) }); assert.equal(oversizedAuth.status, 413);
  const verify = randomToken();
  await db.accountToken.create({ data: { userId: owner.user.id, purpose: "VERIFY_EMAIL", tokenHash: tokenHash(verify), expiresAt: new Date(Date.now() + 60_000) } });
  const verificationResponses = await Promise.all([ownerClient.post("/api/account/verify-email", { token: verify }), ownerClient.post("/api/account/verify-email", { token: verify })]);
  assert.deepEqual(verificationResponses.map(response => response.status).sort(), [200, 400]);
  const expired = randomToken();
  await db.accountToken.create({ data: { userId: owner.user.id, purpose: "RESET_PASSWORD", tokenHash: tokenHash(expired), expiresAt: new Date(Date.now() - 1000) } });
  assert.equal((await anonymous.post("/api/account/reset-password", { token: expired, password: "NewPassword2026!" })).status, 400);
  const reset = randomToken();
  await db.accountToken.update({ where: { userId_purpose: { userId: owner.user.id, purpose: "RESET_PASSWORD" } }, data: { tokenHash: tokenHash(reset), expiresAt: new Date(Date.now() + 60_000) } });
  assert.equal((await anonymous.post("/api/account/reset-password", { token: reset, password: "NewPassword2026!" })).status, 200);
  assert.equal((await anonymous.post("/api/account/reset-password", { token: reset, password: "AnotherPassword2026!" })).status, 400);
  assert.equal((await ownerClient.fetch("/submissions")).status, 307);
  const updatedUser = await db.user.findUniqueOrThrow({ where: { id: owner.user.id } }); assert.equal(updatedUser.sessionVersion, 1); assert.equal(await compare("NewPassword2026!", updatedUser.passwordHash), true);
  console.log("PASS authentication body limits, single-use links, expiry, session invalidation");

  const workerClient = new Client();
  assert.equal((await workerClient.post("/api/jobs/deliveries", {})).status, 401);
  await db.$transaction(tx => removeLead(tx, owner.organizationId, owner.user.id, lead.id));
  assert.equal(await db.outboundDelivery.count({ where: { submissionId: lead.id } }), 0);
  assert.equal((await db.organization.findUniqueOrThrow({ where: { id: owner.organizationId } })).monthlySubmissions, 1);
  assert.equal(await db.activity.count({ where: { organizationId: owner.organizationId, action: "lead.deleted", subjectId: lead.id, submissionId: null } }), 1);
  assert.equal(await db.activity.count({ where: { organizationId: owner.organizationId, subjectId: lead.id, submissionId: null } }), 5);
  console.log("PASS worker authentication and deletion of queued enquiry data");

  const client = await db.$transaction(tx => createClientWorkspace(tx, owner.user.id, owner.organizationId, clientInput(`Client ${suffix}`, "https://client.example/contact"))); orgIds.push(client.id);
  const otherClient = await db.$transaction(tx => createClientWorkspace(tx, outsider.user.id, outsider.organizationId, clientInput(`Outside client ${suffix}`, ""))); orgIds.push(otherClient.id);
  await assert.rejects(() => db.$transaction(tx => createClientWorkspace(tx, viewer.user.id, owner.organizationId, clientInput(`Denied ${suffix}`, ""))), { status: 403 });
  await assert.rejects(() => db.$transaction(tx => createClientWorkspace(tx, outsider.user.id, owner.organizationId, clientInput(`Denied ${suffix}`, ""))), { status: 403 });
  assert.deepEqual((await clientWorkspaces(owner.user.id)).map(row => row.organization.id), [client.id]);
  assert.equal((await clientWorkspaces(viewer.user.id)).length, 0);
  await ownerClient.login(owner.user.email, "NewPassword2026!");
  const clientsPage = await ownerClient.fetch("/clients"); const clientsHtml = await clientsPage.text();
  assert.ok(clientsHtml.includes(client.name) && !clientsHtml.includes(otherClient.name));
  const writer = await fixture("Writer", "MEMBER", owner.organizationId);
  const routingKey = createFormKey();
  const routingForm = await db.form.create({ data: { name: "Routing test", slug: `routing-${suffix}`, organizationId: owner.organizationId, schema, keyHash: routingKey.hash, keyPrefix: routingKey.prefix, allowedOrigins: ["https://allowed.example"] } });
  const sendRouting = (path: string, data = payload, origin = "https://allowed.example", key = routingKey.key) => fetch(`${base}/api/v1/forms/${routingForm.slug}/${path}`, { method: "POST", headers: { Origin: origin, "X-Form-Key": key, "Content-Type": "application/json" }, body: JSON.stringify(data) });
  const usageBefore = (await db.organization.findUniqueOrThrow({ where: { id: owner.organizationId } })).monthlySubmissions;
  assert.equal((await sendRouting("verify", payload, "https://evil.example")).status, 403);
  assert.equal((await sendRouting("verify", payload, undefined, "wrong-key")).status, 404);
  assert.equal((await sendRouting("verify", { ...payload, email: "invalid" })).status, 422);
  const verified = await sendRouting("verify"); assert.equal(verified.status, 200); assert.equal((await verified.json()).test, true);
  assert.equal(verified.headers.get("access-control-allow-origin"), "https://allowed.example");
  assert.equal(await db.submission.count({ where: { formId: routingForm.id } }), 0);
  assert.equal(await db.outboundDelivery.count({ where: { formId: routingForm.id } }), 0);
  assert.equal((await db.organization.findUniqueOrThrow({ where: { id: owner.organizationId } })).monthlySubmissions, usageBefore);
  assert.ok((await db.form.findUniqueOrThrow({ where: { id: routingForm.id } })).connectionCheckedAt);
  assert.equal((await outsiderClient.fetch(`/forms/${routingForm.id}/connect`)).status, 200);
  const outsideConnect = await outsiderClient.fetch(`/forms/${routingForm.id}/connect`); assert.ok(!(await outsideConnect.text()).includes("Routing test"));
  const routingState = { assignmentMode: "DEFAULT" as const, defaultAssigneeId: outsider.user.id, assignmentMemberIds: [], unassignedAlertMinutes: null };
  let version = (await db.form.findUniqueOrThrow({ where: { id: routingForm.id } })).updatedAt;
  await assert.rejects(() => db.$transaction(tx => saveRouting(tx, owner.organizationId, owner.user.id, routingForm.id, version, routingState)), { status: 400 });
  await assert.rejects(() => db.$transaction(tx => saveRouting(tx, owner.organizationId, viewer.user.id, routingForm.id, version, { ...routingState, defaultAssigneeId: owner.user.id })), { status: 403 });
  await db.$transaction(tx => saveRouting(tx, owner.organizationId, owner.user.id, routingForm.id, version, { ...routingState, defaultAssigneeId: owner.user.id }));
  const assigned = await sendRouting("submissions"); assert.equal(assigned.status, 201); const assignedLead = (await assigned.json()).submission;
  assert.equal((await db.submission.findUniqueOrThrow({ where: { id: assignedLead.id } })).assigneeId, owner.user.id);
  assert.equal(await db.activity.count({ where: { submissionId: assignedLead.id, action: "lead.auto_assigned" } }), 1);
  version = (await db.form.findUniqueOrThrow({ where: { id: routingForm.id } })).updatedAt;
  await db.$transaction(tx => saveRouting(tx, owner.organizationId, owner.user.id, routingForm.id, version, { assignmentMode: "ROUND_ROBIN", defaultAssigneeId: null, assignmentMemberIds: [owner.user.id, writer.user.id], unassignedAlertMinutes: null }));
  const rotated = await Promise.all(Array.from({ length: 6 }, () => sendRouting("submissions")));
  assert.ok(rotated.every(response => response.status === 201));
  const rotations = await db.submission.findMany({ where: { formId: routingForm.id, id: { not: assignedLead.id } } });
  assert.equal(rotations.filter(lead => lead.assigneeId === owner.user.id).length, 3);
  assert.equal(rotations.filter(lead => lead.assigneeId === writer.user.id).length, 3);
  await db.organizationMember.update({ where: { userId_organizationId: { userId: writer.user.id, organizationId: owner.organizationId } }, data: { role: "VIEWER" } });
  const afterRemoval = await sendRouting("submissions"); assert.equal(afterRemoval.status, 201);
  assert.equal((await db.submission.findUniqueOrThrow({ where: { id: (await afterRemoval.json()).submission.id } })).assigneeId, owner.user.id);
  await db.form.update({ where: { id: routingForm.id }, data: { assignmentMode: "NONE", unassignedAlertMinutes: 15, notificationEmails: [owner.user.email] } });
  const unassignedLead = await db.submission.create({ data: { formId: routingForm.id, data: payload, schemaSnapshot: schema, createdAt: new Date(Date.now() - 16 * 60_000) } });
  await Promise.all([queueUnassignedAlerts(), queueUnassignedAlerts()]);
  assert.equal(await db.outboundDelivery.count({ where: { submissionId: unassignedLead.id } }), 1);
  await db.submission.update({ where: { id: unassignedLead.id }, data: { assigneeId: owner.user.id } });
  const staleAlert = await db.outboundDelivery.findFirstOrThrow({ where: { submissionId: unassignedLead.id } });
  assert.equal((await processDeliveries([staleAlert.id])).sent, 0);
  assert.equal((await db.outboundDelivery.findUniqueOrThrow({ where: { id: staleAlert.id } })).status, "SKIPPED");
  const freshAlertLead = await db.submission.create({ data: { formId: routingForm.id, data: payload, schemaSnapshot: schema, createdAt: new Date(Date.now() - 16 * 60_000) } });
  await queueUnassignedAlerts();
  const freshAlert = await db.outboundDelivery.findFirstOrThrow({ where: { submissionId: freshAlertLead.id } });
  const alertFetch = globalThis.fetch; let alertSends = 0;
  process.env.RESEND_API_KEY = "test-only"; process.env.MAIL_FROM = "test@example.test";
  globalThis.fetch = async (_url, init) => { alertSends++; assert.ok(String(init?.body).includes("Unassigned enquiry")); assert.ok(!String(init?.body).includes("lead@example.test")); return new Response("", { status: 200 }); };
  try { assert.equal((await processDeliveries([freshAlert.id])).sent, 1); assert.equal(alertSends, 1); }
  finally { globalThis.fetch = alertFetch; delete process.env.RESEND_API_KEY; delete process.env.MAIL_FROM; }
  console.log("PASS client-workspace isolation, dry-run verification, concurrent round robin, removed-member filtering and stale-alert suppression");

  const batchForm = await db.form.create({ data: { name: "Bulk inbox test", slug: `bulk-${suffix}`, organizationId: owner.organizationId, schema, keyHash: tokenHash(randomToken()), keyPrefix: "test" } });
  await db.submission.createMany({ data: Array.from({ length: 30 }, (_, i) => ({ formId: batchForm.id, data: { name: `Batch enquiry ${String(i).padStart(2, "0")}`, email: "batch@example.test" }, schemaSnapshot: schema })) });
  let batchLeads = await db.submission.findMany({ where: { formId: batchForm.id }, orderBy: { id: "asc" } });
  const snapshots = () => batchLeads.slice(0, 2).map(lead => ({ id: lead.id, updatedAt: lead.updatedAt.toISOString() }));
  const batchInput = () => ({ items: snapshots(), change: { kind: "status", value: "CONTACTED" } });
  await assert.rejects(() => db.$transaction(tx => bulkSaveLeads(tx, owner.organizationId, viewer.user.id, batchInput())), { status: 403 });
  await assert.rejects(() => db.$transaction(tx => bulkSaveLeads(tx, outsider.organizationId, outsider.user.id, batchInput())), { status: 404 });
  await assert.rejects(() => db.$transaction(tx => bulkSaveLeads(tx, owner.organizationId, owner.user.id, { ...batchInput(), change: { kind: "assignee", value: outsider.user.id } })), { status: 400 });
  await db.submission.update({ where: { id: batchLeads[1].id }, data: { status: "QUALIFIED", updatedAt: new Date(batchLeads[1].updatedAt.getTime() + 1000) } });
  await assert.rejects(() => db.$transaction(tx => bulkSaveLeads(tx, owner.organizationId, owner.user.id, batchInput())), { status: 409 });
  assert.equal((await db.submission.findUniqueOrThrow({ where: { id: batchLeads[0].id } })).status, "NEW");
  assert.equal(await db.activity.count({ where: { submissionId: { in: batchLeads.map(lead => lead.id) } } }), 0);
  batchLeads = await db.submission.findMany({ where: { formId: batchForm.id }, orderBy: { id: "asc" } });
  const parallelBatch = await Promise.allSettled([db.$transaction(tx => bulkSaveLeads(tx, owner.organizationId, owner.user.id, batchInput())), db.$transaction(tx => bulkSaveLeads(tx, owner.organizationId, owner.user.id, batchInput()))]);
  assert.equal(parallelBatch.filter(result => result.status === "fulfilled").length, 1);
  const firstBatchContacted = await db.submission.findMany({ where: { id: { in: snapshots().map(item => item.id) } } });
  assert.ok(firstBatchContacted.every(lead => lead.status === "CONTACTED" && lead.firstContactedAt));
  assert.equal(await db.activity.count({ where: { submissionId: { in: firstBatchContacted.map(lead => lead.id) }, action: "lead.updated" } }), 2);
  const runBatch = async (change: unknown) => {
    const rows = await db.submission.findMany({ where: { id: { in: firstBatchContacted.map(lead => lead.id) } } });
    await db.$transaction(tx => bulkSaveLeads(tx, owner.organizationId, owner.user.id, { items: rows.map(lead => ({ id: lead.id, updatedAt: lead.updatedAt.toISOString() })), change }));
  };
  await runBatch({ kind: "status", value: "CONTACTED" });
  assert.equal(await db.activity.count({ where: { submissionId: { in: firstBatchContacted.map(lead => lead.id) }, action: "lead.updated" } }), 2, "No-op bulk saves must not add activity");
  await assert.rejects(() => db.$transaction(tx => bulkSaveLeads(tx, owner.organizationId, owner.user.id, { ...batchInput(), items: [...snapshots(), { id: "deleted-enquiry", updatedAt: new Date().toISOString() }] })), { status: 404 });
  await runBatch({ kind: "assignee", value: owner.user.id });
  await runBatch({ kind: "read", value: true });
  await runBatch({ kind: "followup", value: "2026-10-03" });
  let changedBatch = await db.submission.findMany({ where: { id: { in: firstBatchContacted.map(lead => lead.id) } } });
  assert.ok(changedBatch.every(lead => lead.assigneeId === owner.user.id && lead.readAt && lead.followUpAt?.toISOString() === "2026-10-03T00:00:00.000Z"));
  await db.submission.updateMany({ where: { id: { in: changedBatch.map(lead => lead.id) } }, data: { followUpNotifiedAt: new Date(), unassignedNotifiedAt: new Date() } });
  await runBatch({ kind: "followup", value: "" }); await runBatch({ kind: "assignee", value: null }); await runBatch({ kind: "read", value: false });
  changedBatch = await db.submission.findMany({ where: { id: { in: firstBatchContacted.map(lead => lead.id) } } });
  assert.ok(changedBatch.every(lead => !lead.assigneeId && !lead.readAt && !lead.followUpAt && !lead.followUpNotifiedAt && !lead.unassignedNotifiedAt && lead.firstContactedAt));
  const privateView = await db.$transaction(tx => saveInboxView(tx, owner.organizationId, owner.user.id, "Agency priorities", { form: batchForm.id, view: "unassigned", layout: "board", sort: "oldest" }));
  await assert.rejects(() => db.$transaction(tx => saveInboxView(tx, owner.organizationId, owner.user.id, " agency PRIORITIES ", {})), { status: 400 });
  await assert.rejects(() => db.$transaction(tx => saveInboxView(tx, outsider.organizationId, outsider.user.id, "Outside form", { form: batchForm.id })), { status: 400 });
  await assert.rejects(() => db.$transaction(tx => saveInboxView(tx, owner.organizationId, outsider.user.id, "No access", {})), { status: 403 });
  await assert.rejects(() => db.$transaction(tx => removeInboxView(tx, owner.organizationId, viewer.user.id, privateView.id)), { status: 404 });
  const viewerView = await db.$transaction(tx => saveInboxView(tx, owner.organizationId, viewer.user.id, "Viewer priorities", {}));
  const ownerInbox = await ownerClient.fetch(`/submissions?form=${batchForm.id}`); const ownerInboxHtml = await ownerInbox.text();
  assert.ok(ownerInboxHtml.includes("Agency priorities") && !ownerInboxHtml.includes("Viewer priorities") && ownerInboxHtml.includes("Select all enquiries on this page") && !ownerInboxHtml.includes("Bulk enquiry updates") && ownerInboxHtml.includes("Page <!-- -->1<!-- --> of <!-- -->2"));
  const viewerInbox = await viewerClient.fetch(`/submissions?form=${batchForm.id}`); const viewerInboxHtml = await viewerInbox.text();
  assert.ok(viewerInboxHtml.includes("Viewer priorities") && !viewerInboxHtml.includes("Agency priorities") && !viewerInboxHtml.includes("Select all enquiries on this page") && !viewerInboxHtml.includes("Bulk enquiry updates"));
  const outsiderInbox = await outsiderClient.fetch(`/submissions?form=${batchForm.id}&layout=board`); const outsiderInboxHtml = await outsiderInbox.text();
  assert.ok(!outsiderInboxHtml.includes("Batch enquiry") && !outsiderInboxHtml.includes("Agency priorities"));
  const pipeline = await ownerClient.fetch(`/submissions?form=${batchForm.id}&layout=board`); const pipelineHtml = await pipeline.text();
  assert.ok(pipelineHtml.includes("Enquiry pipeline") && pipelineHtml.includes("View all <!-- -->28") && pipelineHtml.includes("Move enquiry"));
  const viewerPipeline = await viewerClient.fetch(`/submissions?form=${batchForm.id}&layout=board`);
  assert.ok(!(await viewerPipeline.text()).includes("Move enquiry"));
  const searchPage = await ownerClient.fetch(`/submissions?form=${batchForm.id}&q=Batch%20enquiry%2001&layout=board`);
  const searchHtml = await searchPage.text(); assert.ok(searchHtml.includes("Batch enquiry 01") && !searchHtml.includes("Batch enquiry 02"));
  const noWonDue = await ownerClient.fetch(`/submissions?form=${batchForm.id}&status=WON&view=overdue`);
  assert.ok((await noWonDue.text()).includes("0 enquiries"));
  const bulkPath = "/api/submissions/bulk";
  const bulkRow = await db.submission.findUniqueOrThrow({ where: { id: firstBatchContacted[0].id } });
  const bulkRequest = { items: [{ id: bulkRow.id, updatedAt: bulkRow.updatedAt.toISOString() }], change: { kind: "read", value: true } };
  assert.equal((await anonymous.post(bulkPath, bulkRequest)).status, 401);
  assert.equal((await viewerClient.post(bulkPath, bulkRequest)).status, 403);
  assert.equal((await outsiderClient.post(bulkPath, bulkRequest)).status, 404);
  assert.equal((await ownerClient.fetch(bulkPath, { method: "POST", headers: { Origin: "https://evil.example", "Content-Type": "application/json" }, body: JSON.stringify(bulkRequest) })).status, 403);
  assert.equal((await ownerClient.fetch(bulkPath, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(bulkRequest) })).status, 403);
  assert.equal((await ownerClient.post(bulkPath, { items: [], change: { kind: "read", value: true } })).status, 400);
  assert.equal((await ownerClient.post(bulkPath, { padding: "x".repeat(12001) })).status, 413);
  const bulkResponse = await ownerClient.post(bulkPath, bulkRequest);
  assert.equal(bulkResponse.status, 200);
  assert.deepEqual(await bulkResponse.json(), { success: "Saved 1 enquiry." });
  assert.ok((await db.submission.findUniqueOrThrow({ where: { id: bulkRow.id } })).readAt);
  assert.equal((await ownerClient.post(bulkPath, bulkRequest)).status, 409);
  const nextBulkRow = await db.submission.findUniqueOrThrow({ where: { id: bulkRow.id } });
  assert.equal((await ownerClient.post(bulkPath, { items: [{ id: bulkRow.id, updatedAt: nextBulkRow.updatedAt.toISOString() }], change: { kind: "read", value: false } })).status, 200);
  assert.equal((await db.submission.findUniqueOrThrow({ where: { id: bulkRow.id } })).readAt, null);
  for (let i = 1; i < 20; i++) await db.$transaction(tx => saveInboxView(tx, owner.organizationId, owner.user.id, `View ${i}`, {}));
  await assert.rejects(() => db.$transaction(tx => saveInboxView(tx, owner.organizationId, owner.user.id, "Too many", {})), { status: 400 });
  await db.$transaction(tx => removeInboxView(tx, owner.organizationId, viewer.user.id, viewerView.id));
  assert.equal(await db.savedInboxView.count({ where: { userId: viewer.user.id } }), 0);
  console.log("PASS atomic bulk updates, authenticated same-origin JSON saves, stale-write rollback, read-only roles, private saved views, scoped pipeline counts and view limits");

  const responder = await fixture("Responder", "MEMBER", owner.organizationId);
  const templateAdmin = await fixture("TemplateAdmin", "ADMIN", owner.organizationId);
  const templateInput = { name: "Agency welcome", subject: "Hello {{name}}", body: "Private reply draft for {{name}} from {{sender_name}}" };
  const template = await db.$transaction(tx => saveReplyTemplate(tx, owner.organizationId, owner.user.id, templateInput));
  for (const actor of [viewer.user, responder.user, outsider.user]) await assert.rejects(() => db.$transaction(tx => saveReplyTemplate(tx, owner.organizationId, actor.id, { ...templateInput, name: "Denied template" })), { status: 403 });
  await assert.rejects(() => db.$transaction(tx => saveReplyTemplate(tx, owner.organizationId, owner.user.id, { ...templateInput, name: " agency WELCOME " })), { status: 400 });
  await assert.rejects(() => db.$transaction(tx => saveReplyTemplate(tx, outsider.organizationId, outsider.user.id, templateInput, { id: template.id, updatedAt: template.updatedAt })), { status: 404 });
  const templateVersion = { id: template.id, updatedAt: template.updatedAt };
  const editedTemplate = await db.$transaction(tx => saveReplyTemplate(tx, owner.organizationId, templateAdmin.user.id, { ...templateInput, subject: "Your enquiry" }, templateVersion));
  assert.ok(editedTemplate.updatedAt > template.updatedAt);
  await assert.rejects(() => db.$transaction(tx => saveReplyTemplate(tx, owner.organizationId, owner.user.id, templateInput, templateVersion)), { status: 409 });
  await assert.rejects(() => db.$transaction(tx => removeReplyTemplate(tx, owner.organizationId, owner.user.id, template.id, template.updatedAt)), { status: 409 });
  await db.$transaction(tx => saveReplyTemplate(tx, owner.organizationId, owner.user.id, { ...templateInput, subject: "Your enquiry" }, { id: editedTemplate.id, updatedAt: editedTemplate.updatedAt }));
  const templateActivity = await db.activity.findMany({ where: { subjectId: template.id } });
  assert.equal(templateActivity.length, 2, "No-op saves must not add activity");
  assert.ok(!JSON.stringify(templateActivity).includes("Private reply draft"));
  await db.user.update({ where: { id: templateAdmin.user.id }, data: { emailVerifiedAt: null } });
  await assert.rejects(() => db.$transaction(tx => saveReplyTemplate(tx, owner.organizationId, templateAdmin.user.id, { ...templateInput, name: "Unverified" })), { status: 403 });
  await db.user.update({ where: { id: templateAdmin.user.id }, data: { emailVerifiedAt: new Date() } });
  await db.organizationMember.update({ where: { userId_organizationId: { userId: templateAdmin.user.id, organizationId: owner.organizationId } }, data: { role: "MEMBER" } });
  await assert.rejects(() => db.$transaction(tx => removeReplyTemplate(tx, owner.organizationId, templateAdmin.user.id, template.id, editedTemplate.updatedAt)), { status: 403 });
  const outsideTemplates = await outsiderClient.fetch("/templates"); assert.ok(!(await outsideTemplates.text()).includes("Agency welcome"));
  const viewerTemplates = await viewerClient.fetch("/templates"); const viewerTemplatesHtml = await viewerTemplates.text();
  assert.ok(viewerTemplatesHtml.includes("Agency welcome") && !viewerTemplatesHtml.includes("Save template") && !viewerTemplatesHtml.includes("Delete template"));
  await db.replyTemplate.createMany({ data: Array.from({ length: 28 }, (_, index) => ({ name: `Quota template ${index}`, subject: "Hello", body: "Message", organizationId: owner.organizationId })) });
  const cappedTemplates = await Promise.allSettled([0, 1].map(index => db.$transaction(tx => saveReplyTemplate(tx, owner.organizationId, owner.user.id, { ...templateInput, name: `Last template ${index}` }))));
  assert.equal(cappedTemplates.filter(result => result.status === "fulfilled").length, 1);
  assert.equal(await db.replyTemplate.count({ where: { organizationId: owner.organizationId } }), 30);
  await db.$transaction(tx => removeReplyTemplate(tx, owner.organizationId, owner.user.id, template.id, editedTemplate.updatedAt));
  assert.equal(await db.activity.count({ where: { subjectId: template.id, action: "reply_template.deleted" } }), 1);
  console.log("PASS reply-template permissions, stale-save protection, private audit data and concurrent workspace limits");

  const repeatedEmail = "repeat@example.test";
  const relatedLead = await db.submission.create({ data: { formId: batchForm.id, data: { name: "Repeat contact", email: "Repeat@Example.Test" }, schemaSnapshot: schema, contactEmail: repeatedEmail } });
  await db.submission.createMany({ data: Array.from({ length: 6 }, (_, index) => ({ formId: routingForm.id, data: { name: `Related ${index}`, email: repeatedEmail }, schemaSnapshot: schema, contactEmail: repeatedEmail })) });
  const spamRelated = await db.submission.create({ data: { formId: batchForm.id, data: { email: repeatedEmail }, schemaSnapshot: schema, contactEmail: repeatedEmail, status: "SPAM" } });
  const outsideForm = await db.form.create({ data: { name: "Outside contact", slug: `outside-contact-${suffix}`, organizationId: outsider.organizationId, schema, keyHash: tokenHash(randomToken()), keyPrefix: "test" } });
  const outsideRelated = await db.submission.create({ data: { formId: outsideForm.id, data: { email: repeatedEmail }, schemaSnapshot: schema, contactEmail: repeatedEmail } });
  const related = await relatedEnquiries(owner.organizationId, relatedLead.id);
  assert.equal(related.total, 6); assert.equal(related.items.length, 5);
  assert.ok(related.items.every(item => ![relatedLead.id, spamRelated.id, outsideRelated.id].includes(item.id)));
  assert.equal((await relatedEnquiries(outsider.organizationId, relatedLead.id)).total, 0);
  assert.equal((await relatedEnquiries(owner.organizationId, spamRelated.id)).total, 0);
  assert.equal(primaryContactEmail({ version: 1, fields: [{ id: "email", label: "Email text", type: "text", required: false }] }, { email: repeatedEmail }), null);
  const relatedOwnerPage = await ownerClient.fetch(`/submissions/${relatedLead.id}`); const relatedOwnerHtml = await relatedOwnerPage.text();
  assert.ok(relatedOwnerHtml.includes("Same email") && relatedOwnerHtml.includes("Open email draft") && relatedOwnerHtml.includes("repeat@example.test"));
  const relatedViewerPage = await viewerClient.fetch(`/submissions/${relatedLead.id}`); const relatedViewerHtml = await relatedViewerPage.text();
  assert.ok(relatedViewerHtml.includes("Same email") && !relatedViewerHtml.includes("Reply draft") && !relatedViewerHtml.includes("Open email draft"));
  assert.equal((await db.submission.findUniqueOrThrow({ where: { id: relatedLead.id } })).status, "NEW");
  assert.equal(await db.activity.count({ where: { submissionId: relatedLead.id } }), 0, "Opening drafts must not record a sent/contacted event");
  console.log("PASS conservative email matching, workspace-only related enquiries, bounded results and read-only draft access");

  await db.form.update({ where: { id: routingForm.id }, data: { webhookUrl: "https://webhook.example/hook", webhookSecret: encrypt("private-webhook-secret"), connectionCheckedAt: new Date(), connectionCheckedVersion: 1 } });
  const sourceBeforeCopy = await db.form.findUniqueOrThrow({ where: { id: routingForm.id } });
  for (const actor of [viewer.user, responder.user, outsider.user]) await assert.rejects(() => db.$transaction(tx => duplicateFormInWorkspace(tx, owner.organizationId, actor.id, routingForm.id, "Denied copy")), { status: 403 });
  await assert.rejects(() => db.$transaction(tx => duplicateFormInWorkspace(tx, outsider.organizationId, outsider.user.id, routingForm.id, "Outside copy")), { status: 404 });
  await db.user.update({ where: { id: owner.user.id }, data: { emailVerifiedAt: null } });
  await assert.rejects(() => db.$transaction(tx => duplicateFormInWorkspace(tx, owner.organizationId, owner.user.id, routingForm.id, "Unverified copy")), { status: 403 });
  await db.user.update({ where: { id: owner.user.id }, data: { emailVerifiedAt: new Date() } });
  const copy = await db.$transaction(tx => duplicateFormInWorkspace(tx, owner.organizationId, owner.user.id, routingForm.id, "Copied routing form"));
  const copiedForm = await db.form.findUniqueOrThrow({ where: { id: copy.id } });
  assert.equal(copiedForm.status, "DRAFT"); assert.notEqual(copiedForm.slug, sourceBeforeCopy.slug); assert.notEqual(copiedForm.keyHash, sourceBeforeCopy.keyHash);
  assert.equal(copiedForm.keyHash, tokenHash(copy.key));
  assert.deepEqual(copiedForm.schema, sourceBeforeCopy.schema); assert.deepEqual(copiedForm.allowedOrigins, sourceBeforeCopy.allowedOrigins);
  assert.deepEqual(copiedForm.notificationEmails, []); assert.equal(copiedForm.webhookUrl, null); assert.equal(copiedForm.webhookSecret, null);
  assert.equal(copiedForm.assignmentMode, "NONE"); assert.equal(copiedForm.defaultAssigneeId, null); assert.deepEqual(copiedForm.assignmentMemberIds, []);
  assert.equal(copiedForm.unassignedAlertMinutes, null); assert.equal(copiedForm.connectionCheckedAt, null); assert.equal(copiedForm.connectionCheckedVersion, null);
  assert.equal(copiedForm.schemaVersion, 1); assert.equal(copiedForm.assignmentCursor, 0);
  assert.equal(await db.submission.count({ where: { formId: copy.id } }), 0); assert.equal(await db.outboundDelivery.count({ where: { formId: copy.id } }), 0);
  assert.deepEqual(await db.form.findUniqueOrThrow({ where: { id: routingForm.id } }), sourceBeforeCopy);
  const duplicationActivity = await db.activity.findFirstOrThrow({ where: { subjectId: copy.id, action: "form.duplicated" } });
  assert.ok(!JSON.stringify(duplicationActivity).includes(copy.key) && !JSON.stringify(duplicationActivity).includes("private-webhook-secret"));
  console.log("PASS scoped form duplication, verified-role rechecks, fresh keys and safe draft defaults");

  const agendaNow = new Date();
  const agendaDay = new Date(`${agendaNow.toISOString().slice(0, 10)}T00:00:00.000Z`);
  const scheduledDay = (offset: number) => new Date(agendaDay.getTime() + offset * 86400_000);
  const agendaForm = await db.form.create({ data: { name: "Agenda enquiries", slug: `agenda-${suffix}`, organizationId: owner.organizationId, schema, keyHash: tokenHash(randomToken()), keyPrefix: "test" } });
  await db.submission.createMany({ data: [
    ...Array.from({ length: 27 }, (_, index) => ({ formId: agendaForm.id, data: { name: `Agenda contact ${index}`, email: `agenda${index}@example.test` }, schemaSnapshot: schema, status: "NEW" as const, followUpAt: agendaDay, assigneeId: index % 3 === 0 ? owner.user.id : index % 3 === 1 ? responder.user.id : null })),
    ...[-2, -1, 1, 7, 8].map(offset => ({ formId: agendaForm.id, data: { name: `Agenda offset ${offset}` }, schemaSnapshot: schema, followUpAt: scheduledDay(offset), assigneeId: owner.user.id })),
    ...(["WON", "LOST", "SPAM"] as const).map(status => ({ formId: agendaForm.id, data: { name: `Excluded ${status}` }, schemaSnapshot: schema, followUpAt: agendaDay, status })),
    { formId: agendaForm.id, data: { name: "Unscheduled" }, schemaSnapshot: schema },
  ] });
  await db.submission.update({ where: { id: outsideRelated.id }, data: { followUpAt: agendaDay } });
  const agendaFilters = followUpFilters({ period: "today", form: agendaForm.id });
  const agenda = await followUpAgenda(owner.organizationId, owner.user.id, agendaFilters, 999, agendaNow);
  assert.equal(agenda.total, 27); assert.equal(agenda.page, 2); assert.equal(agenda.pages, 2); assert.equal(agenda.rows.length, 2);
  assert.deepEqual(agenda.counts, { overdue: 2, today: 27, upcoming: 2, all: 32 });
  assert.ok(agenda.rows.every(row => row.form.id === agendaForm.id && row.status === "NEW"));
  assert.equal((await followUpAgenda(owner.organizationId, owner.user.id, { ...agendaFilters, assignee: "mine" }, 1, agendaNow)).total, 9);
  assert.equal((await followUpAgenda(owner.organizationId, owner.user.id, { ...agendaFilters, assignee: "unassigned" }, 1, agendaNow)).total, 9);
  assert.equal((await followUpAgenda(outsider.organizationId, outsider.user.id, agendaFilters, 1, agendaNow)).total, 0);
  assert.equal((await followUpAgenda(owner.organizationId, owner.user.id, { ...agendaFilters, form: outsideForm.id }, 1, agendaNow)).total, 0);
  const agendaOwnerPage = await ownerClient.fetch(`/follow-ups?period=today&form=${agendaForm.id}`); const agendaOwnerHtml = await agendaOwnerPage.text();
  assert.equal(agendaOwnerPage.status, 200); assert.ok(agendaOwnerHtml.includes("Save follow-up date") && agendaOwnerHtml.includes("Page <!-- -->1<!-- --> of <!-- -->2"));
  const agendaViewerPage = await viewerClient.fetch(`/follow-ups?period=today&form=${agendaForm.id}`); const agendaViewerHtml = await agendaViewerPage.text();
  assert.ok(agendaViewerHtml.includes("Agenda contact") && !agendaViewerHtml.includes("Save follow-up date") && !agendaViewerHtml.includes("Clear follow-up"));
  const unavailableAgenda = await outsiderClient.fetch(`/follow-ups?period=today&form=${agendaForm.id}`); const unavailableAgendaHtml = await unavailableAgenda.text();
  assert.ok(unavailableAgendaHtml.includes("Unavailable form") && !unavailableAgendaHtml.includes("Agenda contact") && !unavailableAgendaHtml.includes("Agenda enquiries"));
  const agendaLead = await db.submission.findFirstOrThrow({ where: { formId: agendaForm.id, status: "NEW", followUpAt: agendaDay } });
  const reminderLead = await db.submission.update({ where: { id: agendaLead.id }, data: { followUpNotifiedAt: new Date() } });
  const moveFollowUp = (actorId: string, updatedAt: Date, value: string) => db.$transaction(tx => bulkSaveLeads(tx, owner.organizationId, actorId, { items: [{ id: agendaLead.id, updatedAt: updatedAt.toISOString() }], change: { kind: "followup", value } }));
  await assert.rejects(() => moveFollowUp(viewer.user.id, reminderLead.updatedAt, scheduledDay(1).toISOString().slice(0, 10)), { status: 403 });
  await moveFollowUp(owner.user.id, reminderLead.updatedAt, scheduledDay(1).toISOString().slice(0, 10));
  const rescheduledLead = await db.submission.findUniqueOrThrow({ where: { id: agendaLead.id } });
  assert.equal(rescheduledLead.followUpAt?.getTime(), scheduledDay(1).getTime()); assert.equal(rescheduledLead.followUpNotifiedAt, null);
  assert.equal(rescheduledLead.status, reminderLead.status); assert.equal(rescheduledLead.assigneeId, reminderLead.assigneeId); assert.equal(rescheduledLead.readAt, reminderLead.readAt); assert.equal(rescheduledLead.firstContactedAt, reminderLead.firstContactedAt);
  await assert.rejects(() => moveFollowUp(owner.user.id, reminderLead.updatedAt, ""), { status: 409 });
  await moveFollowUp(owner.user.id, rescheduledLead.updatedAt, "");
  assert.equal((await db.submission.findUniqueOrThrow({ where: { id: agendaLead.id } })).followUpAt, null);
  await assert.rejects(() => db.$transaction(tx => addLeadNote(tx, owner.organizationId, viewer.user.id, agendaLead.id, "Denied note")), { status: 403 });
  await assert.rejects(() => db.$transaction(tx => removeLead(tx, owner.organizationId, responder.user.id, agendaLead.id)), { status: 403 });
  const revoked = await fixture("Revoked", "ADMIN", owner.organizationId);
  await db.organizationMember.delete({ where: { userId_organizationId: { userId: revoked.user.id, organizationId: owner.organizationId } } });
  await assert.rejects(() => db.$transaction(tx => addLeadNote(tx, owner.organizationId, revoked.user.id, agendaLead.id, "Revoked note")), { status: 403 });
  await assert.rejects(() => db.$transaction(tx => removeLead(tx, owner.organizationId, revoked.user.id, agendaLead.id)), { status: 403 });
  assert.equal(await db.submissionNote.count({ where: { submissionId: agendaLead.id } }), 0);
  assert.equal(await db.activity.count({ where: { submissionId: agendaLead.id } }), 2);
  console.log("PASS UTC follow-up buckets, scoped counts/pagination, viewers, stale reschedules and revoked note/delete access");

  const search = await ownerClient.fetch(`/api/search?q=${encodeURIComponent("Agenda contact")}`);
  assert.equal(search.status, 200); assert.equal(search.headers.get("cache-control"), "private, no-store");
  const searchResults = (await search.json()).results;
  assert.equal(searchResults.length, 10);
  assert.ok(searchResults.every((result: { kind: string; title: string; href: string }) => result.kind === "enquiry" && result.title.startsWith("Agenda contact") && result.href.startsWith("/submissions/")));
  assert.deepEqual((await (await outsiderClient.fetch("/api/search?q=Agenda%20contact")).json()).results, []);
  assert.equal((await anonymous.fetch("/api/search?q=Agenda")).status, 401);
  assert.equal((await viewerClient.fetch("/api/search?q=Agenda%20contact")).status, 200);
  const formSearch = (await (await ownerClient.fetch("/api/search?q=Agenda%20enquiries")).json()).results;
  assert.ok(formSearch.some((result: { kind: string; href: string }) => result.kind === "form" && result.href === `/forms/${agendaForm.id}`));
  for (const query of ["a", "%", "x".repeat(121)]) assert.deepEqual((await (await ownerClient.fetch(`/api/search?q=${encodeURIComponent(query)}`)).json()).results, []);
  assert.deepEqual((await (await ownerClient.fetch("/api/search?q=%25%25")).json()).results, [], "Search wildcards must be treated literally");
  const publicDemo = await anonymous.fetch("/demo"); assert.equal(publicDemo.status, 200); assert.ok((await publicDemo.text()).includes("Fieldwork Studio"));
  await db.user.update({ where: { id: viewer.user.id }, data: { sessionVersion: { increment: 1 } } });
  assert.equal((await viewerClient.fetch("/api/search?q=Agenda")).status, 401);
  console.log("PASS authenticated bounded workspace search, tenant isolation, viewers, expired sessions and public fictional demo");

  const originalFetch = globalThis.fetch;
  process.env.RESEND_API_KEY = "test-only"; process.env.MAIL_FROM = "test@example.test";
  const job = await db.outboundDelivery.create({ data: mailJob(owner.user.email, "Integration mail", "Test only") }); jobIds.push(job.id);
  let sends = 0;
  globalThis.fetch = async () => { sends++; return new Response("", { status: sends === 1 ? 503 : 200 }); };
  try {
    await processDeliveries([job.id]);
    const pending = await db.outboundDelivery.findUniqueOrThrow({ where: { id: job.id } }); assert.equal(pending.status, "PENDING"); assert.equal(pending.attempts, 1); assert.ok(pending.nextAttemptAt > new Date());
    await db.outboundDelivery.update({ where: { id: job.id }, data: { nextAttemptAt: new Date(0) } });
    await Promise.all([processDeliveries([job.id]), processDeliveries([job.id])]);
    assert.equal(sends, 2); assert.equal((await db.outboundDelivery.findUniqueOrThrow({ where: { id: job.id } })).status, "SENT");
  } finally { globalThis.fetch = originalFetch; delete process.env.RESEND_API_KEY; delete process.env.MAIL_FROM; }
  const unsafeWebhook = await db.form.create({ data: { name: "Unsafe hook", slug: `unsafe-${suffix}`, organizationId: owner.organizationId, schema, keyHash: tokenHash(randomToken()), keyPrefix: "test", webhookUrl: "https://localhost/hook", webhookSecret: encrypt(randomToken()) } });
  const hookJob = await db.outboundDelivery.create({ data: { kind: "WEBHOOK", formId: unsafeWebhook.id, payload: { url: "https://localhost/hook", event: {} } } });
  await processDeliveries([hookJob.id]); assert.equal((await db.outboundDelivery.findUniqueOrThrow({ where: { id: hookJob.id } })).status, "PENDING");
  console.log("PASS delivery retry, exclusive worker claims, SSRF rejection");
  await db.form.update({ where: { id: form.id }, data: { notificationEmails: [] } });
  const disabledMail = await db.outboundDelivery.create({ data: mailJob(owner.user.email, "Disabled alert", "Should not send", undefined, form.id) });
  const skipped = await processDeliveries([disabledMail.id]);
  assert.equal(skipped.sent, 0);
  assert.equal((await db.outboundDelivery.findUniqueOrThrow({ where: { id: disabledMail.id } })).status, "SKIPPED");
  console.log("PASS disabled notifications are recorded as skipped, not sent");

  const timestamp = String(Math.floor(Date.now() / 1000)); const body = '{"id":"evt_test"}'; const signature = webhookSignature(body, timestamp, "webhook-secret");
  assert.equal(verifyStripeSignature(body, `t=${timestamp},v1=${signature}`, "webhook-secret"), true);
  assert.equal(verifyStripeSignature(body + " ", `t=${timestamp},v1=${signature}`, "webhook-secret"), false);
  assert.equal(verifyStripeSignature(body, `t=1,v1=${signature}`, "webhook-secret"), false);
  process.env.BILLING_ENABLED = "true"; process.env.STRIPE_SECRET_KEY = "test"; process.env.STRIPE_WEBHOOK_SECRET = "test"; process.env.STRIPE_PRO_PRICE_ID = "price_test"; process.env.FREE_FORM_LIMIT = "2";
  await assert.rejects(() => db.$transaction(tx => checkQuota(tx, owner.organizationId, "forms")), { status: 429 });
  await assert.rejects(() => db.$transaction(tx => duplicateFormInWorkspace(tx, owner.organizationId, owner.user.id, routingForm.id, "Over quota copy")), { status: 429 });
  const formsBeforeConcurrentCopy = await db.form.count({ where: { organizationId: owner.organizationId, status: { not: "ARCHIVED" } } });
  process.env.FREE_FORM_LIMIT = String(formsBeforeConcurrentCopy + 1);
  const quotaCopies = await Promise.allSettled([0, 1].map(index => db.$transaction(tx => duplicateFormInWorkspace(tx, owner.organizationId, owner.user.id, routingForm.id, `Quota copy ${index}`))));
  assert.equal(quotaCopies.filter(result => result.status === "fulfilled").length, 1);
  assert.equal(await db.form.count({ where: { organizationId: owner.organizationId, status: { not: "ARCHIVED" } } }), formsBeforeConcurrentCopy + 1);
  delete process.env.BILLING_ENABLED; delete process.env.STRIPE_SECRET_KEY; delete process.env.STRIPE_WEBHOOK_SECRET; delete process.env.STRIPE_PRO_PRICE_ID; delete process.env.FREE_FORM_LIMIT;
  assert.equal(decrypt(encrypt("secret")), "secret");
  console.log("PASS billing signatures, replay window and quota enforcement");
} finally {
  await db.outboundDelivery.deleteMany({ where: { id: { in: jobIds } } });
  await db.organization.deleteMany({ where: { id: { in: orgIds } } });
  await db.user.deleteMany({ where: { id: { in: userIds } } });
  await db.$disconnect();
}
