import Link from "next/link";
import { LegalContact, LegalDocument } from "@/components/legal-document";
import { publicMetadata } from "@/lib/site/seo";

export const dynamic = "force-dynamic";
export const metadata = publicMetadata("Terms of Service", "The agreement for using d3CRM workspaces, website form integrations, and optional subscriptions.", "/terms");

export default function TermsPage() {
  return <LegalDocument title="Terms of Service" intro="These terms govern your use of d3CRM when you expressly accept them. “We” means the operator identified below; “you” means the person or business accepting the agreement.">
    <section className="resource-section"><h2>1. Agreement and eligibility</h2><p>You must be at least 18 and authorized to act for the business whose workspace you create or use. A person accepting for a business confirms that authority. The <Link href="/data-processing">Data Processing Agreement</Link> forms part of these terms for customer personal data; it takes priority on that subject. A separately signed service order takes priority on its agreed commercial provisions. The <Link href="/privacy">Privacy Policy</Link> describes processing; accepting these terms is not blanket consent to personal-data use.</p></section>
    <section className="resource-section"><h2>2. What the service provides</h2><p>d3CRM receives website-form enquiries and provides a shared inbox, forms, assignments, notes, follow-up scheduling, templates, campaign context, reports, and CSV exports. Email alerts, webhooks, and subscriptions depend on enabled services and configuration. A reply draft opens your own email application; it does not send through d3CRM. Follow-up dates use UTC.</p><p>You must test your website integration and monitor failures and quota limits. A successful endpoint test does not prove notification delivery, legal compliance, or installation on a website. Publishable form keys identify a form and are visible to website visitors. d3CRM is not an emergency, medical, financial, legal, or compliance-certification service.</p></section>
    <section className="resource-section"><h2>3. Accounts and workspace access</h2><p>Provide accurate information, protect login credentials, and tell us promptly about unauthorized access. You are responsible for authorized account activity, integrations, and access you grant. Owners control invitations, membership, and ownership transfer. Viewers can read and export. Agency access persists while the agency remains a member; review and remove access during client handover. We may require verification before restoring access or changing ownership.</p></section>
    <section className="resource-section"><h2>4. Customer data and lawful collection</h2><p>You retain your rights in your content. You grant us permission to host, process, transmit, and display it only to deliver and secure the service, carry out your instructions, and comply with law. We do not receive a right to sell customer data or train AI models on it.</p><p>You must have authority and a lawful ground to collect, submit, access, and disclose every record. Publish your own notice at the form, collect and preserve any required consent, keep optional marketing separate, honor rights requests, and set a retention process. You are responsible for customer-selected webhooks, downloaded copies, external email drafts, and information copied to an AI agent. Do not submit children’s or specially regulated sensitive data unless we have first agreed appropriate lawful safeguards in writing. Do not place secrets or sensitive information in ordinary enquiry fields or URLs.</p></section>
    <section className="resource-section"><h2>5. Acceptable use</h2><p>Do not use d3CRM for unlawful collection, spam, harassment, fraud, impersonation, malware, rights infringement, or unauthorized disclosure. Do not bypass access controls or limits, probe other workspaces, scrape private records, or disrupt the service. Report suspected security problems privately to the legal contact; do not access unrelated customer data. We may investigate misuse and preserve evidence as lawfully necessary.</p></section>
    <section className="resource-section"><h2>6. Plans, payments, and cancellation</h2><p>Charges apply only when you approve a paid checkout or separately agreed order. The checkout/order sets the price, currency, taxes, billing period, renewal, and applicable cancellation details; these terms invent no price or trial. Recurring plans renew as disclosed until cancelled. Workspace plans and limits are separate, including client workspaces. The service may reject new submissions when a limit is reached; deleting old enquiries does not reset monthly usage.</p><p>If subscriptions are enabled, the workspace owner can manage cancellation through the configured Stripe portal, or contact us if the portal is unavailable. Cancellation takes effect as disclosed at checkout or confirmed by support; it does not itself delete data. Refunds follow the checkout/order and applicable law; mandatory refund, cancellation, and consumer rights always apply. We will give advance notice of price changes before they affect a renewal.</p></section>
    <section className="resource-section"><h2>7. Availability and changes</h2><p>We use reasonable care in operating the service but do not promise uninterrupted service, exact-time reminders, guaranteed email/webhook delivery, or a particular business outcome. Providers, networks, maintenance, and customer configuration can affect performance. Keep suitable copies of records and review failures. We will give reasonable advance notice of material service reductions where practicable; security or legal issues may require immediate action. Any separately agreed service-level commitment remains applicable.</p></section>
    <section className="resource-section"><h2>8. Suspension, closure, and export</h2><p>We may restrict access proportionately for a material breach, non-payment of agreed fees, credible security risk, or a legal requirement. Where reasonable, we explain the reason and allow a chance to fix it. Immediate action may be necessary to protect people or data.</p><p>You may stop using the service and request account or workspace closure using the contact below. Export available enquiries before closure. Where lawful and safe, we provide a reasonable opportunity to export before planned termination. Erasure and return of customer personal data follow the Data Processing Agreement and legal obligations. Removing a member, archiving a form, or cancelling a plan does not delete a workspace. We verify workspace authority and protect other members’ rights before closure.</p></section>
    <section className="resource-section"><h2>9. Intellectual property</h2><p>The software, product design, and d3CRM branding belong to us or our licensors; you receive a limited right to use the service under this agreement. Third-party software retains its own license. You may offer feedback; we may use it without paying compensation, but feedback does not grant rights to your confidential or personal data.</p></section>
    <section className="resource-section"><h2>10. Warranties and liability</h2><p>To the extent permitted by law, the service is provided as available without additional implied warranties of merchantability, fitness for a particular purpose, or non-infringement. We remain responsible for expressly agreed commitments and mandatory obligations.</p><p>For business customers, to the extent permitted by law, neither party is liable to the other for indirect or consequential losses, lost profits, or lost business opportunities. Each party’s total contractual liability arising from the service is limited to the greater of fees paid or payable for the affected workspace in the 12 months preceding the event and INR 10,000.</p><p>These exclusions and limits do not apply to fraud, wilful misconduct, gross negligence, death or personal injury caused by negligence, unpaid agreed fees, or liability that applicable law does not allow to be excluded or limited. They do not restrict individual privacy rights, regulator powers, mandatory data-protection liability, or non-waivable consumer remedies. Nothing prevents a lawful complaint or claim.</p></section>
    <section className="resource-section"><h2>11. Disputes and general terms</h2><p>Contact us with a concern so we can try to resolve it. Indian law governs this agreement, subject to mandatory local protections. Courts with lawful jurisdiction may hear disputes; there is no mandatory arbitration, class-action waiver, or waiver of access to a regulator. Consumers retain any mandatory rights to the law and courts of their residence.</p><p>If a provision is unenforceable, the rest continues to apply. A failure to enforce a provision is not a waiver. Neither party may transfer the agreement in a way that reduces the other party’s mandatory rights; a lawful business succession must preserve contractual and data-protection duties. Provisions that need to survive closure, including payment, confidentiality, and valid liability terms, survive.</p><p>We publish a new version and give reasonable notice of material amendments. Where renewed agreement is required, we request it; posting a change alone does not create a new recorded acceptance. Changes apply prospectively and do not retroactively waive claims. Legal notices go to the operator contact below and account notices go to the verified account address.</p></section>
    <LegalContact />
  </LegalDocument>;
}
